CREATE TABLE AuditLogs (
    Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
    TimestampWib DATETIME2(3) NOT NULL CONSTRAINT DF_AuditLogs_Timestamp DEFAULT SYSUTCDATETIME(),
    TraceId NVARCHAR(100) NULL,
    UserId NVARCHAR(100) NULL,
    UserName NVARCHAR(150) NULL,
    ClientType NVARCHAR(20) NOT NULL,
    IpAddress NVARCHAR(50) NULL,
    UserAgent NVARCHAR(500) NULL,
    Action NVARCHAR(100) NOT NULL,
    EntityName NVARCHAR(100) NULL,
    EntityId NVARCHAR(100) NULL,
    Status NVARCHAR(20) NOT NULL,
    Details NVARCHAR(MAX) NULL
);

CREATE NONCLUSTERED INDEX IX_AuditLogs_TimestampWib ON AuditLogs (TimestampWib DESC);
CREATE NONCLUSTERED INDEX IX_AuditLogs_UserId ON AuditLogs (UserId);
CREATE NONCLUSTERED INDEX IX_AuditLogs_Action ON AuditLogs (Action);